name: flutter_checkauthentication
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amplify_flutter: 0.1.4
  amplify_analytics_pinpoint: 0.1.4
  amplify_auth_cognito: 0.1.4
  amplify_storage_s3: 0.1.4
  cupertino_icons: ^1.0.2
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/